password_webapp_project/accounts_app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'accounts_app'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name="accounts_app/login.html"), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('afterLogout/', views.AfterLogoutView.as_view(), name="afterLogout"),
    path('register/', views.RegisterView.as_view(), name='register'),

    path('password_reset/', views.PasswordResetRequest.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name="accounts_app/password_reset_done.html"),
         name='password_reset_done'),
    path('reset_password/<uidb64>/(<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts_app/password_reset_confirm.html"),
         name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name="accounts_app/password_reset_complete.html"),
         name='password_reset_complete'),

    path('account_settings/', views.AccountSettingsView.as_view(), name='account_settings'),
    path('account_change_password/', views.AccountChangePasswordView.as_view(), name='account_change_password'),
    path('account_change_email/', views.AccountChangeEmailView.as_view(), name='account_change_email'),

]

password_webapp_project/password_webapp_project/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import IndexView

urlpatterns = [
    path("", IndexView.as_view(), name='index'),
    path("password/", include('password_app.urls')),
    path("password/", include('password_import_export_app.urls', namespace="password_import_export_app")),
    path('accounts/', include('accounts_app.urls', namespace='accounts_app')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

# Only in development. Delete it on production server
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns += staticfiles_urlpatterns()

password_webapp_project/accounts_app/models.py
from django.db import models

# Create your models here.

password_webapp_project/accounts_app/forms.py
from django import forms

from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class UserCreateForm(UserCreationForm):
    class Meta:
        fields = ('username', 'email', 'first_name',
                  'last_name', 'password1', 'password2')
        model = get_user_model()


class UserEmailChangeForm(forms.Form):
    email = forms.EmailField(label="Email", max_length=1000, required=True)


class UserPasswordChangeForm(forms.Form):
    password = forms.CharField(label="Hasło", widget=forms.PasswordInput(), max_length=1000, required=True)
    password2 = forms.CharField(label="Hasło raz jeszcze", widget=forms.PasswordInput(), max_length=1000, required=True)

    def clean(self):
        cleaned_data = super(UserPasswordChangeForm, self).clean()
        password = cleaned_data.get('password')
        password2 = cleaned_data.get('password2')

        if password and password2 and password != password2:
            self._errors['password2'] = self.error_class(['Hasła muszą być takie same.'])
            del self.cleaned_data['password2']
        return cleaned_data

password_webapp_project/accounts_app/views.py
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import BadHeaderError, send_mail
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.views import generic

from .forms import *


class AfterLogoutView(generic.TemplateView):
    template_name = "accounts_app/after_logout.html"


class RegisterView(generic.CreateView):
    form_class = UserCreateForm
    success_url = reverse_lazy('accounts_app:login')
    template_name = 'accounts_app/register.html'


class AccountSettingsView(LoginRequiredMixin, generic.TemplateView):
    template_name = "accounts_app/account_settings.html"


class AccountChangeEmailView(LoginRequiredMixin, generic.FormView):
    template_name = "accounts_app/account_change_email.html"
    form_class = UserEmailChangeForm
    success_url = reverse_lazy("accounts_app:account_settings")

    def get_initial(self, *args, **kwargs):
        initial = super(AccountChangeEmailView, self).get_initial(**kwargs)
        initial['email'] = self.request.user.email
        return initial

    def form_valid(self, form):
        email_from_form = form.cleaned_data['email']

        user = self.request.user
        user_obj = User.objects.get(pk=user.pk)
        user_obj.email = email_from_form
        user_obj.save()

        return super(AccountChangeEmailView, self).form_valid(form)


class AccountChangePasswordView(LoginRequiredMixin, generic.FormView):
    template_name = "accounts_app/account_change_password.html"
    form_class = UserPasswordChangeForm
    success_url = reverse_lazy("accounts_app:account_settings")

    def form_valid(self, form):
        password_from_form = form.cleaned_data['password']

        user = self.request.user
        user_obj = User.objects.get(pk=user.pk)
        user_obj.set_password(raw_password=password_from_form)
        user_obj.save()

        return super(AccountChangePasswordView, self).form_valid(form)


class PasswordResetRequest(generic.View):

    def post(self, request):
        password_reset_form = PasswordResetForm(request.POST)
        if password_reset_form.is_valid():
            email_from_form = password_reset_form.cleaned_data['email']
            user_obj_qs = User.objects.filter(Q(email=email_from_form))

            if user_obj_qs.exists():
                for user_obj in user_obj_qs:
                    subject = "Resetowanie hasła"
                    email_template_name = "accounts_app/password_reset_email_body_template.txt"
                    mail_body = self.build_mail_body(request, user_obj, email_template_name)

                    try:
                        send_mail(subject, mail_body, 'reset_password@mail.com', [user_obj.email], fail_silently=False)
                    except BadHeaderError:
                        return HttpResponse('Invalid header found.')
                    return redirect(reverse_lazy("accounts_app:password_reset_done"))

    def get(self, request):
        password_reset_form = PasswordResetForm()

        return render(request=request, template_name="accounts_app/password_reset.html",
                      context={"form": password_reset_form})

    def build_mail_body(self, request, user_obj, email_template_name):
        c = {
            "email": user_obj.email,
            "full_name": user_obj.get_full_name(),
            'page_full_url': request.build_absolute_uri('/')[:-1],
            "uid": urlsafe_base64_encode(force_bytes(user_obj.id)),
            'token': default_token_generator.make_token(user_obj),
        }
        return render_to_string(email_template_name, c)

password_webapp_project/templates/accounts_app/account_change_email.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block page_content %}

<h3>Zmień email</h3>
<form method="post" novalidate>
    {% csrf_token %}

    {% for hidden_field in form.hidden_fields %}
    {{ hidden_field }}
    {% endfor %}

    {% if form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {% for error in form.non_field_errors %}
        {{ error }}
        {% endfor %}
    </div>
    {% endif %}

    {% for field in form.visible_fields %}
    <div class="form-group">
        {{ field.label_tag }}

        {% if form.is_bound %}
        {% if field.errors %}
        {% render_field field class="form-control is-invalid col-md-6" %}
        {% for error in field.errors %}
        <div class="invalid-feedback">
            {{ error }}
        </div>
        {% endfor %}
        {% else %}
        {% render_field field class="form-control is-valid col-md-6" %}
        {% endif %}
        {% else %}
        {% render_field field class="form-control col-md-6" %}
        {% endif %}

        {% if field.help_text %}
        <small class="form-text text-muted">{{ field.help_text }}</small>
        {% endif %}
    </div>
    {% endfor %}

    <button type="submit" class="btn btn-outline-secondary">Zmień</button>
</form>

<div style="margin: 30px 0px 30px 0px;">
    <a href="{% url 'accounts_app:account_settings' %}">
        <button class="btn btn-outline-secondary">Powrót</button>
    </a>
</div>


{% endblock page_content %}

password_webapp_project/templates/accounts_app/account_change_password.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block page_content %}

<h3>Zmień hasło</h3>
<p></b>Uwaga: </b>Po zmianie hasła zostaniesz wylogowany/a</p>
<form method="post" novalidate>
    {% csrf_token %}

    {% for hidden_field in form.hidden_fields %}
    {{ hidden_field }}
    {% endfor %}

    {% if form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {% for error in form.non_field_errors %}
        {{ error }}
        {% endfor %}
    </div>
    {% endif %}

    {% for field in form.visible_fields %}
    <div class="form-group">
        {{ field.label_tag }}

        {% if form.is_bound %}
        {% if field.errors %}
        {% render_field field class="form-control is-invalid col-md-6" %}
        {% for error in field.errors %}
        <div class="invalid-feedback">
            {{ error }}
        </div>
        {% endfor %}
        {% else %}
        {% render_field field class="form-control is-valid col-md-6" %}
        {% endif %}
        {% else %}
        {% render_field field class="form-control col-md-6" %}
        {% endif %}

        {% if field.help_text %}
        <small class="form-text text-muted">{{ field.help_text }}</small>
        {% endif %}
    </div>
    {% endfor %}


    <button type="submit" class="btn btn-outline-secondary">Zmień</button>

</form>

<div style="margin: 30px 0px 30px 0px;">
    <a href="{% url 'accounts_app:account_settings' %}">
        <button class="btn btn-outline-secondary">Powrót</button>
    </a>
</div>


{% endblock page_content %}

password_webapp_project/templates/accounts_app/account_settings.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block page_content %}

<h3>Twoje konto</h3>

<div style="margin-top:30px;">
    <p>Twoje dane:</p>
    <ul>
        <li><b>Imię i nazwisko:</b> {{ user.get_full_name }}</li>
        <li><b>Adres email:</b> {{ user.email }}</li>
        <li><b>Ostatnio zalogowany:</b> {{ user.last_login }}</li>
        <li><b>Data rejestracji:</b> {{ user.date_joined }}</li>
    </ul>
</div>

<div class="btn-group" role="group">
  <div class="btn-group mr-2" role="group">
      <a href="{% url 'accounts_app:account_change_password' %}">
        <button type="button" class="btn btn-outline-secondary">Zmień hasło</button>
      </a>
  </div>

  <div class="btn-group mr-2" role="group">
      <a href="{% url 'accounts_app:account_change_email' %}">
        <button type="button" class="btn btn-outline-secondary">Zmień adres email</button>
      </a>
  </div>
</div>

{% endblock page_content %}

password_webapp_project/templates/accounts_app/after_logout.html
{% extends "base.html" %}

{% block page_content %}

    <h3>Wylogowano</h3>

{% endblock page_content %}

password_webapp_project/templates/accounts_app/login.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block page_content %}

<h3>Zaloguj się</h3>
<form method="post" novalidate>
    {% csrf_token %}

    {% for hidden_field in form.hidden_fields %}
    {{ hidden_field }}
    {% endfor %}

    {% if form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {% for error in form.non_field_errors %}
        {{ error }}
        {% endfor %}
    </div>
    {% endif %}

    {% for field in form.visible_fields %}
    <div class="form-group">
        {{ field.label_tag }}

        {% if form.is_bound %}
        {% if field.errors %}
        {% render_field field class="form-control is-invalid col-md-6" %}
        {% for error in field.errors %}
        <div class="invalid-feedback">
            {{ error }}
        </div>
        {% endfor %}
        {% else %}
        {% render_field field class="form-control is-valid col-md-6" %}
        {% endif %}
        {% else %}
        {% render_field field class="form-control col-md-6" %}
        {% endif %}

        {% if field.help_text %}
        <small class="form-text text-muted">{{ field.help_text }}</small>
        {% endif %}
    </div>
    {% endfor %}

    <button type="submit" class="btn btn-outline-secondary">Zaloguj się</button>
</form>

<div style="margin: 30px 0px 30px 0px;">
    <a class="btn btn-outline-secondary" href="#">Zresetuj hasło</a>
</div>


{% endblock page_content %}

password_webapp_project/templates/accounts_app/password_reminder_mail_template.html
<!DOCTYPE html>
<html lang="en">
<body>
    <p>Hi.</p>
    <p><b>Passwords below will expire soon:</b></p>
    <br>
    {% for password_obj in passwords_objects_list %}
        <ul>
            <li>Password description: '{{password_obj.description}}', Expiration date: {{password_obj.expiration_date}}</li>
        </ul>
    {% endfor %}
    <br>
    <p>Password Manager</p>
</body>
</html>

password_webapp_project/templates/accounts_app/password_reset.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block page_content %}

<h3>Reset hasła</h3>
<form method="post" novalidate>
    {% csrf_token %}

    {% for hidden_field in form.hidden_fields %}
    {{ hidden_field }}
    {% endfor %}

    {% if form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {% for error in form.non_field_errors %}
        {{ error }}
        {% endfor %}
    </div>
    {% endif %}

    {% for field in form.visible_fields %}
    <div class="form-group">
        {{ field.label_tag }}

        {% if form.is_bound %}
        {% if field.errors %}
        {% render_field field class="form-control is-invalid col-md-6" %}
        {% for error in field.errors %}
        <div class="invalid-feedback">
            {{ error }}
        </div>
        {% endfor %}
        {% else %}
        {% render_field field class="form-control is-valid col-md-6" %}
        {% endif %}
        {% else %}
        {% render_field field class="form-control col-md-6" %}
        {% endif %}

        {% if field.help_text %}
        <small class="form-text text-muted">{{ field.help_text }}</small>
        {% endif %}
    </div>
    {% endfor %}

    <button type="submit" class="btn btn-outline-secondary">Wyślij</button>
</form>


{% endblock page_content %}

password_webapp_project/templates/accounts_app/password_reset_complete.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block page_content %}

<h3>Hasło zostało zmienione</h3>


{% endblock page_content %}

password_webapp_project/templates/accounts_app/password_reset_confirm.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block page_content %}

<h3>Zmień hasło</h3>
<form method="post" novalidate>
    {% csrf_token %}

    {% for hidden_field in form.hidden_fields %}
    {{ hidden_field }}
    {% endfor %}

    {% if form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {% for error in form.non_field_errors %}
        {{ error }}
        {% endfor %}
    </div>
    {% endif %}

    {% for field in form.visible_fields %}
    <div class="form-group">
        {{ field.label_tag }}

        {% if form.is_bound %}
        {% if field.errors %}
        {% render_field field class="form-control is-invalid col-md-6" %}
        {% for error in field.errors %}
        <div class="invalid-feedback">
            {{ error }}
        </div>
        {% endfor %}
        {% else %}
        {% render_field field class="form-control is-valid col-md-6" %}
        {% endif %}
        {% else %}
        {% render_field field class="form-control col-md-6" %}
        {% endif %}

        {% if field.help_text %}
        <small class="form-text text-muted">{{ field.help_text }}</small>
        {% endif %}
    </div>
    {% endfor %}

    <button type="submit" class="btn btn-outline-secondary">Zmień</button>
</form>


{% endblock page_content %}

password_webapp_project/templates/accounts_app/password_reset_done.html
{% extends "base.html" %}

{% block page_content %}

  <p>
    Mail został wysłany. Kliknij na link w wiadomości, aby zresetować hasło.
  </p>
  <p>
    Jeśli nie otrzymałeś maila, sprawdź czy ustawiłeś poprawny adres email w ustawieniach konta.
    Sprawdź także folder spam w poczcie.
  </p>

{% endblock page_content %}

password_webapp_project/templates/accounts_app/register.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block page_content %}

<h3>Rejestracja</h3>
<form method="post" novalidate>
    {% csrf_token %}

    {% for hidden_field in form.hidden_fields %}
    {{ hidden_field }}
    {% endfor %}

    {% if form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {% for error in form.non_field_errors %}
        {{ error }}
        {% endfor %}
    </div>
    {% endif %}

    {% for field in form.visible_fields %}
    <div class="form-group">
        {{ field.label_tag }}

        {% if form.is_bound %}
        {% if field.errors %}
        {% render_field field class="form-control is-invalid col-md-6" %}
        {% for error in field.errors %}
        <div class="invalid-feedback">
            {{ error }}
        </div>
        {% endfor %}
        {% else %}
        {% render_field field class="form-control is-valid col-md-6" %}
        {% endif %}
        {% else %}
        {% render_field field class="form-control col-md-6" %}
        {% endif %}

        {% if field.help_text %}
        <small class="form-text text-muted">{{ field.help_text }}</small>
        {% endif %}
    </div>
    {% endfor %}

    <button type="submit" class="btn btn-outline-secondary">Zarejestruj się</button>
</form>


{% endblock page_content %}