password_webapp_project/accounts_app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'accounts_app'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name="accounts_app/login.html"), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('afterLogout/', views.AfterLogoutView.as_view(), name="afterLogout"),
    path('register/', views.RegisterView.as_view(), name='register'),

    path('password_reset/', views.PasswordResetRequest.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name="accounts_app/password_reset_done.html"),
         name='password_reset_done'),
    path('reset_password/<uidb64>/(<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts_app/password_reset_confirm.html"),
         name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name="accounts_app/password_reset_complete.html"),
         name='password_reset_complete'),

    path('account_settings/', views.AccountSettingsView.as_view(), name='account_settings'),
    path('account_change_password/', views.AccountChangePasswordView.as_view(), name='account_change_password'),
    path('account_change_email/', views.AccountChangeEmailView.as_view(), name='account_change_email'),

]

password_webapp_project/password_app/urls.py
from django.urls import path

from . import views

app_name = 'password_app'
urlpatterns = [
    path('', views.PasswordListView.as_view(), name='list'),
    path('show/<int:pk>/', views.PasswordDetailView.as_view(), name='detail'),
    path('add/', views.PasswordCreateView.as_view(), name='add'),
    path('update/<int:pk>/', views.PasswordUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.PasswordDeleteView.as_view(), name='delete'),
    path('remove_from_shared/<int:pk>/', views.RemoveUserFromSharedPasswordUsers.as_view(), name='remove_from_shared'),
]

password_webapp_project/password_import_export_app/urls.py
from django.urls import path

from . import views

app_name = 'password_import_export_app'
urlpatterns = [
    path('export_csv/', views.PasswordExportToCSV.as_view(), name='export_to_csv'),
    path('import_csv/upload/', views.PasswordImportFromCsvFile.as_view(), name='import_from_csv_upload'),
    path('import_csv/load/', views.PasswordImportFromCsvFileLoadData.as_view(), name='import_from_csv_load'),
]

password_webapp_project/password_webapp_project/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import IndexView

urlpatterns = [
    path("", IndexView.as_view(), name='index'),
    path("password/", include('password_app.urls')),
    path("password/", include('password_import_export_app.urls', namespace="password_import_export_app")),
    path('accounts/', include('accounts_app.urls', namespace='accounts_app')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

# Only in development. Delete it on production server
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns += staticfiles_urlpatterns()

password_webapp_project/password_import_export_app/models.py
from django.db import models

# Create your models here.

password_webapp_project/password_import_export_app/forms.py
from django import forms


class PasswordCsvFileUploadForm(forms.Form):
    csv_file = forms.FileField(label="", widget=forms.FileInput(attrs={'accept': ".csv"}))

password_webapp_project/password_import_export_app/views.py
import csv
import json
from typing import List, Dict, Tuple

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render
from django.views import generic
from django.core.exceptions import ObjectDoesNotExist

from password_app.models import Password
from .forms import PasswordCsvFileUploadForm
from .utils.password_export_import_utils import parse_password_to_csv_file, csv_fieldnames_list, \
    csv_required_fields_list


class PasswordExportToCSV(LoginRequiredMixin, generic.View):
    def get(self, request):
        # Get user passwords
        curr_user_obj = self.request.user
        q_filter = Q(password_shared_users=curr_user_obj) | Q(password_owner=curr_user_obj)
        passwords_qs = Password.objects.filter(q_filter).distinct()

        # Create the HttpResponse object with the appropriate CSV header.
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = f'attachment; filename="passwords_{curr_user_obj}.csv"'

        # write to csv file
        writer = csv.DictWriter(response, fieldnames=csv_fieldnames_list, delimiter=";")
        writer.writeheader()

        for password in passwords_qs:
            row_dict = parse_password_to_csv_file(password, csv_fieldnames_list)
            writer.writerow(row_dict)

        return response


class PasswordImportFromCsvFile(LoginRequiredMixin, generic.FormView):
    form_class = PasswordCsvFileUploadForm
    template_name = "password_import_export_app/password_csv_import_upload.html"

    def post(self, request, *args, **kwargs):
        # if not len(request.FILES):
        #     return HttpResponseRedirect(reverse_lazy("password_app:list"))

        form = PasswordCsvFileUploadForm(request.POST, request.FILES)
        if form.is_valid():
            fieldnames, upload_file_rows = self.parse_file_rows(request.FILES['csv_file'])
            validate_errors_list = self.validate_csv_rows(fieldnames, upload_file_rows)

            upload_file_rows_json = json.dumps(upload_file_rows)
            if len(validate_errors_list):
                return render(
                    request,
                    template_name="password_import_export_app/password_csv_import_validate_error.html",
                    context={"validate_errors_list": validate_errors_list,
                             "upload_file_rows": upload_file_rows}
                )

            return render(
                request,
                template_name="password_import_export_app/password_csv_import_validate_ok.html",
                context={"upload_file_rows": upload_file_rows,
                         "upload_file_rows_json": upload_file_rows_json}
            )

    def parse_file_rows(self, file, delimiter=";", encoding="utf-8") -> Tuple[List, List[Dict]]:
        rows_list = []
        fieldnames = []
        for i, row in enumerate(file):
            row = row.decode(encoding).replace("\r\n", "")  # rsplit remove endline chars
            row = row.split(delimiter)
            row = [col.strip() for col in row]
            if i == 0:
                fieldnames = row
            else:
                csv_row = dict(zip(fieldnames, row))
                rows_list.append(csv_row)
        return fieldnames, rows_list

    def validate_csv_rows(self, fieldnames_from_file, upload_file_rows: dict):
        errors_list = []

        if fieldnames_from_file != csv_fieldnames_list:
            errors_list.append("Niewłaściwy nagłówek pliku CSV")

        for row_n, file_row in enumerate(upload_file_rows, start=1):
            if len(file_row.keys()) != len(fieldnames_from_file):
                errors_list.append(f"Błąd w wierszu nr {row_n}: Niewłaściwa liczba kolumn w wierszu")

            for required_csv_field in csv_required_fields_list:
                if not len(file_row.get(required_csv_field)):
                    errors_list.append(
                        f"Błąd w wierszu nr {row_n}: Brak wartości dla kolumny \"{required_csv_field}\", w wierszu.")

        return errors_list


class PasswordImportFromCsvFileLoadData(LoginRequiredMixin, generic.TemplateView):

    def post(self, request):
        csv_file_import_data_json = json.loads(request.POST['csv_import_data_json'])

        for password_data_from_csv in csv_file_import_data_json:
            password_owner_username_from_csv = password_data_from_csv.get("password_owner")
            try:
                password_owner_obj = User.objects.get(username=password_owner_username_from_csv)
            except ObjectDoesNotExist:
                continue

            password_obj, is_obj_created = Password.objects.get_or_create(
                description=password_data_from_csv.get("description"),
                password=password_data_from_csv.get("password"),
                expiration_date=password_data_from_csv.get("expiration_date"),
                password_owner=password_owner_obj
            )

            # Add shared users from CSV to password object
            password_shared_users = self.get_password_shared_users_from_csv(password_data_from_csv)
            if is_obj_created and password_shared_users:
                password_obj.password_shared_users.add(*password_shared_users)

        return render(request, "password_import_export_app/password_csv_import_load_success.html",
                      context={
                          "csv_file_import_data_json": csv_file_import_data_json
                      })

    def get_password_shared_users_from_csv(self, password_data_from_csv):
        password_shared_users_from_csv = password_data_from_csv.get("password_shared_users")
        password_shared_users_list = []

        # Parse shared_users from csv to model objects
        if password_shared_users_from_csv != "-":
            password_shared_users_from_csv = password_shared_users_from_csv.split(",")
            for user in password_shared_users_from_csv:
                try:
                    shared_user = User.objects.get(username=user)
                except ObjectDoesNotExist:
                    continue
                password_shared_users_list.append(shared_user)

        return password_shared_users_list if len(password_shared_users_list) > 0 else False

password_webapp_project/templates/password_import_export_app/password_csv_import_load_success.html
{% extends "base.html" %}

{% block page_content %}

<h3>Dodano hasła z pliku CSV</h3>


{% endblock page_content %}

password_webapp_project/templates/password_import_export_app/password_csv_import_upload.html
{% extends "base.html" %}
{% load widget_tweaks %}


{% block page_content %}

<div style="margin: 30px 0px 30px 0px;">
    <a href="{% url 'password_app:list' %}">
        <button class="btn btn-outline-secondary">Powrót</button>
    </a>
</div>

<h3>Importuj hasła z pliku CSV</h3>

<form method="post" enctype="multipart/form-data" novalidate>
    {% csrf_token %}

    {% for hidden_field in form.hidden_fields %}
    {{ hidden_field }}
    {% endfor %}

    {% if form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {% for error in form.non_field_errors %}
        {{ error }}
        {% endfor %}
    </div>
    {% endif %}

    {% for field in form.visible_fields %}
    <div class="form-group">
        {{ field.label_tag }}

        {% if form.is_bound %}
        {% if field.errors %}
        {% render_field field class="form-control is-invalid col-md-6" %}
        {% for error in field.errors %}
        <div class="invalid-feedback">
            {{ error }}
        </div>
        {% endfor %}
        {% else %}
        {% render_field field class="form-control is-valid col-md-6" %}
        {% endif %}
        {% else %}
        {% render_field field class="form-control col-md-6" %}
        {% endif %}

        {% if field.help_text %}
        <small class="form-text text-muted">{{ field.help_text }}</small>
        {% endif %}
    </div>
    {% endfor %}

    <button type="submit" class="btn btn-outline-secondary">Importuj</button>
</form>

{% endblock page_content %}

password_webapp_project/templates/password_import_export_app/password_csv_import_validate_error.html
{% extends "base.html" %}

{% block page_content %}

<h3>Błędna zawartość pliku</h3>

<div style="margin: 30px 0px 30px 0px;">
    <a href="{% url 'password_import_export_app:import_from_csv_upload' %}">
        <button class="btn btn-outline-secondary">Powrót</button>
    </a>
</div>

<table class="password-table table table-hover">
    <thead>
    <th>Błędy</th>
    </thead>

    <tbody>
    {% for csv_error in validate_errors_list %}
    <tr>
        <td>{{ csv_error }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>



{% endblock page_content %}

password_webapp_project/templates/password_import_export_app/password_csv_import_validate_ok.html
{% extends "base.html" %}

{% block page_content %}

<h3>Wczytano wiersze pliku CSV</h3>

<div style="margin: 30px 0px 30px 0px;">
    <a href="{% url 'password_import_export_app:import_from_csv_upload' %}">
        <button class="btn btn-outline-secondary">Powrót</button>
    </a>
</div>

<div>
    <p>Wczytano {{ upload_file_rows|length }} wierszy z pliku CSV</p>

    <table class="password-table table table-hover">
        <thead>
            <th>Opis</th>
            <th>Wygasa</th>
            <th>Właściciel</th>
            <th>Udostępnione użytkownikom</th>
        </thead>

        <tbody>
            {% for password in upload_file_rows %}
            <tr>
                <td>{{password.description}}</td>
                <td>{{password.expiration_date}}</td>
                <td>{{password.password_owner}}</td>
                <td>{{password.password_shared_users}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

</div>

<form method="post" action="{% url 'password_import_export_app:import_from_csv_load' %}">
    {% csrf_token %}
    <textarea type="text" name="csv_import_data_json" hidden>{{ upload_file_rows_json }}</textarea>
    <button type="submit" class="btn btn-outline-secondary">Wgraj</button>
</form>


{% endblock page_content %}