password_webapp_project/accounts_app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'accounts_app'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name="accounts_app/login.html"), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('afterLogout/', views.AfterLogoutView.as_view(), name="afterLogout"),
    path('register/', views.RegisterView.as_view(), name='register'),

    path('password_reset/', views.PasswordResetRequest.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name="accounts_app/password_reset_done.html"),
         name='password_reset_done'),
    path('reset_password/<uidb64>/(<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts_app/password_reset_confirm.html"),
         name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name="accounts_app/password_reset_complete.html"),
         name='password_reset_complete'),

    path('account_settings/', views.AccountSettingsView.as_view(), name='account_settings'),
    path('account_change_password/', views.AccountChangePasswordView.as_view(), name='account_change_password'),
    path('account_change_email/', views.AccountChangeEmailView.as_view(), name='account_change_email'),

]

password_webapp_project/password_app/urls.py
from django.urls import path

from . import views

app_name = 'password_app'
urlpatterns = [
    path('', views.PasswordListView.as_view(), name='list'),
    path('show/<int:pk>/', views.PasswordDetailView.as_view(), name='detail'),
    path('add/', views.PasswordCreateView.as_view(), name='add'),
    path('update/<int:pk>/', views.PasswordUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.PasswordDeleteView.as_view(), name='delete'),
    path('remove_from_shared/<int:pk>/', views.RemoveUserFromSharedPasswordUsers.as_view(), name='remove_from_shared'),
]

password_webapp_project/password_webapp_project/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import IndexView

urlpatterns = [
    path("", IndexView.as_view(), name='index'),
    path("password/", include('password_app.urls')),
    path("password/", include('password_import_export_app.urls', namespace="password_import_export_app")),
    path('accounts/', include('accounts_app.urls', namespace='accounts_app')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

# Only in development. Delete it on production server
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns += staticfiles_urlpatterns()

password_webapp_project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <link href="{% static 'css/main.css' %}"  rel="stylesheet" type="text/css" />
        <link href="{% static 'css/icon.css' %}" rel="stylesheet">
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

        <script src="{% static 'js/jquery-3.5.1.slim.min.js' %}"></script>
        <script src="{% static 'js/popper.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>

    </head>
    <body>


        <div class="sidebar">
            {% if not user.is_authenticated %}
                <a href="{% url 'index' %}">
                    <i class="material-icons">home</i>
                    <span class="menu-elem-text">Home</span>
                </a>

                <a href="{% url 'accounts_app:login' %}">
                    <i class="material-icons">account_box</i>
                    <span class="menu-elem-text">Zaloguj się</span>
                </a>

                <a href="{% url 'accounts_app:register' %}">
                    <i class="material-icons">content_paste</i>
                    <span class="menu-elem-text">Zarejestruj się</span>
                </a>

            {% else %}

                {% if user.first_name %}
                    <p class="logged-as-text">Witaj {{ user.first_name }}</p>
                {% endif %}

                <a style="background-color: #f1f1f1;" class="menu-search">
                    <form name="search-input" target="#here" method="post">
                        {% csrf_token %}
                        <input class="menu-search-input" type="text" placeholder="Szukaj..">
                        <input type="submit" hidden/>
                    </form>
                </a>

                <a href="{% url 'index' %}">
                    <i class="material-icons">home</i>
                    <span class="menu-elem-text">Home</span>
                </a>

                <a href="{% url 'password_app:list' %}">
                    <i class="material-icons">vpn_key</i>
                    <span class="menu-elem-text">Hasła</span>
                </a>
                <a href="{% url 'accounts_app:account_settings' %}">
                    <i class="material-icons">settings</i>
                    <span class="menu-elem-text">Ustawienia</span>
                </a>
                <a href="{% url 'accounts_app:logout' %}">
                    <i class="material-icons">power_settings_new</i>
                    <span class="menu-elem-text">Wyloguj</span>
                </a>
            {% endif %}
        </div>

        <div class="content">
            <div class="container-fluid">
                {% block page_content %}{% endblock %}
            </div>
        </div>

    </body>
</html>

password_webapp_project/templates/index.html
{% extends "base.html" %}

{% block page_content %}

    <h1>Strona główna</h1>

{% endblock page_content %}