password_webapp_project/accounts_app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'accounts_app'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name="accounts_app/login.html"), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('afterLogout/', views.AfterLogoutView.as_view(), name="afterLogout"),
    path('register/', views.RegisterView.as_view(), name='register'),

    path('password_reset/', views.PasswordResetRequest.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name="accounts_app/password_reset_done.html"),
         name='password_reset_done'),
    path('reset_password/<uidb64>/(<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts_app/password_reset_confirm.html"),
         name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name="accounts_app/password_reset_complete.html"),
         name='password_reset_complete'),

    path('account_settings/', views.AccountSettingsView.as_view(), name='account_settings'),
    path('account_change_password/', views.AccountChangePasswordView.as_view(), name='account_change_password'),
    path('account_change_email/', views.AccountChangeEmailView.as_view(), name='account_change_email'),

]

password_webapp_project/password_app/urls.py
from django.urls import path

from . import views

app_name = 'password_app'
urlpatterns = [
    path('', views.PasswordListView.as_view(), name='list'),
    path('show/<int:pk>/', views.PasswordDetailView.as_view(), name='detail'),
    path('add/', views.PasswordCreateView.as_view(), name='add'),
    path('update/<int:pk>/', views.PasswordUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.PasswordDeleteView.as_view(), name='delete'),
    path('remove_from_shared/<int:pk>/', views.RemoveUserFromSharedPasswordUsers.as_view(), name='remove_from_shared'),
]

password_webapp_project/password_import_export_app/urls.py
from django.urls import path

from . import views

app_name = 'password_import_export_app'
urlpatterns = [
    path('export_csv/', views.PasswordExportToCSV.as_view(), name='export_to_csv'),
    path('import_csv/upload/', views.PasswordImportFromCsvFile.as_view(), name='import_from_csv_upload'),
    path('import_csv/load/', views.PasswordImportFromCsvFileLoadData.as_view(), name='import_from_csv_load'),
]

password_webapp_project/password_webapp_project/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import IndexView

urlpatterns = [
    path("", IndexView.as_view(), name='index'),
    path("password/", include('password_app.urls')),
    path("password/", include('password_import_export_app.urls', namespace="password_import_export_app")),
    path('accounts/', include('accounts_app.urls', namespace='accounts_app')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

# Only in development. Delete it on production server
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns += staticfiles_urlpatterns()

password_webapp_project/password_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Password(models.Model):
    description = models.CharField(verbose_name="Opis", max_length=500, default="")
    password = models.CharField(verbose_name="Hasło", max_length=1000, null=False, blank=False)
    expiration_date = models.DateField(verbose_name="Data wygaśnięcia (opcjonalnie)", null=True, blank=True)
    create_date = models.DateField(verbose_name="Data utworzenia", auto_now_add=True)
    modify_date = models.DateField(verbose_name="Data modyfikacji", auto_now=True)
    password_owner = models.ForeignKey(User, verbose_name="Właściciel", default=None, null=True, related_name="+", on_delete=models.CASCADE)
    password_shared_users = models.ManyToManyField(User, verbose_name="Dziel hasło z", related_name="+", blank=True)

    class Meta:
        verbose_name = "Hasło"
        verbose_name_plural = "Hasła"


    def __str__(self):
        return f"{self.description}, user: {self.password_owner.username}"

    # Create and update views will be go to this page after form submit
    def get_absolute_url(self):
        return reverse('password_app:list', args=[str(self.pk)])

password_webapp_project/password_app/forms.py
from django import forms
from django.urls import reverse_lazy

from .models import Password


class PasswordCreateForm(forms.ModelForm):
    expiration_date = forms.DateField(label="Hasło wygasa w dniu", widget=forms.widgets.DateInput(
        format=('%Y-%m-%d'),
        attrs={
            'type': 'date'
        }
    ))

    class Meta:
        model = Password
        exclude = ['password_owner']
        success_url = reverse_lazy('password_app:list')

password_webapp_project/password_app/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from .forms import PasswordCreateForm
from .models import Password


class PasswordListView(LoginRequiredMixin, generic.ListView):
    model = Password
    context_object_name = 'user_passwords'
    template_name = 'password_app/password_list.html'
    paginate_by = 10

    def get_queryset(self):
        curr_user_obj = self.request.user
        q_filter = Q(password_shared_users=curr_user_obj) | Q(password_owner=curr_user_obj)
        qs = Password.objects.filter(q_filter).distinct()
        return qs.order_by('description')


class PasswordDetailView(LoginRequiredMixin, generic.DetailView):
    model = Password
    context_object_name = 'user_password'
    template_name = 'password_app/password_detail.html'


class PasswordCreateView(LoginRequiredMixin, generic.CreateView):
    model = Password
    form_class = PasswordCreateForm
    template_name = 'password_app/password_create.html'

    def get_context_data(self, **kwargs):
        context = super(PasswordCreateView, self).get_context_data(**kwargs)
        curr_user_pk = self.request.user.pk
        context['form'].fields['password_shared_users'].queryset = User.objects.filter(
            ~Q(pk=curr_user_pk))  # ~ means exclude
        return context

    def form_valid(self, form):
        shared_users_qs = form.cleaned_data['password_shared_users']
        self.object = form.save(commit=False)
        self.object.password_owner = self.request.user
        self.object.save()

        # Add shared users to password obj
        self.object.password_shared_users.add(*shared_users_qs)
        self.object.save()
        return HttpResponseRedirect(reverse_lazy("password_app:list"))


class PasswordUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Password
    form_class = PasswordCreateForm
    template_name = "password_app/password_update.html"
    success_url = reverse_lazy("password_app:list")

    def get(self, request, *args, **kwargs):
        request = super().get(request, *args, **kwargs)
        self.object = self.get_object()
        curr_user = self.request.user

        if curr_user is not self.request.user:
            if curr_user not in self.object.password_shared_users.all():
                return HttpResponseRedirect(reverse_lazy("password_app:list"))

        return request

    def get_context_data(self, **kwargs):
        context = super(PasswordUpdateView, self).get_context_data(**kwargs)
        curr_user = self.request.user

        # Don't show password owner user in shared users field
        context['form'].fields['password_shared_users'].queryset = User.objects.filter(
            ~Q(pk=curr_user.pk))  # ~ means exclude

        return context


class PasswordDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Password
    template_name = "password_app/password_delete.html"
    context_object_name = "user_password"
    success_url = reverse_lazy('password_app:list')


class RemoveUserFromSharedPasswordUsers(LoginRequiredMixin, generic.View):
    template_name = "password_app/password_remove_user_from_shared.html"

    def get(self, request, pk):
        current_user = self.request.user
        password_obj = Password.objects.get(pk=pk)

        if current_user not in password_obj.password_shared_users.all():
            return HttpResponseRedirect(reverse_lazy("password_app:list"))
        return render(request, self.template_name, {'password_obj': password_obj})

    def post(self, pk):
        current_user = self.request.user

        password_obj = Password.objects.get(pk=pk)
        if current_user in password_obj.password_shared_users.all():
            password_obj.password_shared_users.remove(current_user)
            password_obj.save()
        return HttpResponseRedirect(reverse_lazy("password_app:list"))

password_webapp_project/templates/password_app/password_create.html
{% extends "base.html" %}
{% load widget_tweaks %}


{% block page_content %}

<div style="margin: 30px 0px 30px 0px;">
    <a href="{% url 'password_app:list' %}">
        <button class="btn btn-outline-secondary">Powrót</button>
    </a>
</div>
<h3>Dodaj hasło</h3>




<form method="post" novalidate>
    {% csrf_token %}

    {% for hidden_field in form.hidden_fields %}
    {{ hidden_field }}
    {% endfor %}

    {% if form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {% for error in form.non_field_errors %}
        {{ error }}
        {% endfor %}
    </div>
    {% endif %}

    {% for field in form.visible_fields %}
    <div class="form-group">
        {{ field.label_tag }}

        {% if form.is_bound %}
        {% if field.errors %}
        {% render_field field class="form-control is-invalid col-md-6" %}
        {% for error in field.errors %}
        <div class="invalid-feedback">
            {{ error }}
        </div>
        {% endfor %}
        {% else %}
        {% render_field field class="form-control is-valid col-md-6" %}
        {% endif %}
        {% else %}
        {% render_field field class="form-control col-md-6" %}
        {% endif %}

        {% if field.help_text %}
        <small class="form-text text-muted">{{ field.help_text }}</small>
        {% endif %}
    </div>
    {% endfor %}

    <button type="submit" class="btn btn-outline-secondary">Dodaj</button>
</form>

{% endblock page_content %}

password_webapp_project/templates/password_app/password_delete.html
{% extends "base.html" %}

{% block page_content %}

<form method="post">
    {% csrf_token %}
    <p>Czy chcesz usunąć hasło: "{{ user_password.description }}"?</p>

    {% if user_password.password_shared_users.count > 0 %}
        <p><b>Uwaga: Jesteś właścicielem tego hasła. Jeśli je usuniesz osoby współdzielące hasło stracą do niego dostęp</b></p>
        <p>Hasło współdzielone z użytkownikami: {{ user_password.password_shared_users.all|join:", " }}</p>
        <p></p>
    {% endif %}

    <input class="btn btn-outline-secondary" type="submit" value="Usuń">

</form>

<div style="margin: 30px 0px 30px 0px;">
    <a href="{% url 'password_app:list' %}">
        <button class="btn btn-outline-secondary">Powrót</button>
    </a>
</div>

{% endblock page_content %}

password_webapp_project/templates/password_app/password_detail.html
{% extends "base.html" %}

{% block page_content %}

	<p>Hasło: id {{user_password.description}}</p>
	<li><a href="{% url 'password_app:detail' user_password.pk %}">Link</a></li>
{% endblock page_content %}

password_webapp_project/templates/password_app/password_list.html
{% extends "base.html" %}

{% block page_content %}

<h3>Twoje hasła</h3>

<div class="table-btns">
    <div class="row">
        <div class="btn-group mr-3">
            <a href="{% url 'password_app:add' %}">
                <button class="btn btn-outline-secondary">Dodaj</button>
            </a>
        </div>

        <div class="col-md-9">
        </div>

        <div class="btn-group mr-3">
            <a href="{% url 'password_import_export_app:export_to_csv' %}"><button class="btn btn-outline-secondary">Export</button></a>
            <a href="{% url 'password_import_export_app:import_from_csv_upload' %}"><button class="btn btn-outline-secondary">Import</button></a>
        </div>
    </div>
</div>

<table class="password-table table table-hover">
    <thead>
    <th></th>
    <th>Opis</th>
    <th>Wygasa</th>
    <th>Właściciel</th>
    <th>Akcje</th>
    </thead>

    <tbody>
    {% for password in user_passwords %}
    <tr>
        <td>
            <i class="material-icons" onclick="copyToClipboard('{{password.password}}')">content_copy</i>
        </td>
        <td>{{password.description}}</td>
        <td>{{password.expiration_date}}</td>
        <td>{{password.password_owner}}</td>
        <td>
            <i data-toggle="collapse" data-target="#accordion-{{password.pk}}" class="material-icons">info</i>
            <a href="{% url 'password_app:update' password.pk %}"><i class="material-icons">edit</i></a>

            {% if user == password.password_owner %}
                <a href="{% url 'password_app:delete' password.pk %}"><i class="material-icons">delete_forever</i></a>
            {% else %}
                <a href="{% url 'password_app:remove_from_shared' password.pk %}"><i class="material-icons">delete</i></a>
            {% endif %}
        </td>
    </tr>
    <tr id="accordion-{{password.pk}}" class="collapse">
        <td colspan="3">
            <div>
                <ul>
                    {% if password.password_shared_users.count > 0 %}
                        <li><b>Hasło dzielone z użytkownikami: </b>{{ password.password_shared_users.all|join:", " }}</li>
                    {% endif %}
                    <li><b>Data utworzenia: </b>{{password.create_date}}</li>
                    <li><b>Data modyfikacji: </b>{{password.modify_date}}</li>
                </ul>
            </div>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>

<script>
/**
 * Copy a string to clipboard
 * @param  {String} string         The string to be copied to clipboard
 * @return {Boolean}               returns a boolean correspondent to the success of the copy operation.
 */
function copyToClipboard(string) {
  let textarea;
  let result;

  try {
    textarea = document.createElement('textarea');
    textarea.setAttribute('readonly', true);
    textarea.setAttribute('contenteditable', true);
    textarea.style.position = 'fixed'; // prevent scroll from jumping to the bottom when focus is set.
    textarea.value = string;

    document.body.appendChild(textarea);

    textarea.focus();
    textarea.select();

    const range = document.createRange();
    range.selectNodeContents(textarea);

    const sel = window.getSelection();
    sel.removeAllRanges();
    sel.addRange(range);

    textarea.setSelectionRange(0, textarea.value.length);
    result = document.execCommand('copy');
    alert("Hasło skopiowane");
  } catch (err) {
    console.error(err);
    result = null;
  } finally {
    document.body.removeChild(textarea);
  }

  // manual copy fallback using prompt
  if (!result) {
    const isMac = navigator.platform.toUpperCase().indexOf('MAC') >= 0;
    const copyHotkey = isMac ? '⌘C' : 'CTRL+C';
    result = prompt(`Press ${copyHotkey}`, string); // eslint-disable-line no-alert
    if (!result) {
      return false;
    }
  }
  return true;
}
</script>

{% endblock page_content %}

password_webapp_project/templates/password_app/password_remove_user_from_shared.html
{% extends "base.html" %}

{% block page_content %}

<form method="post">
    {% csrf_token %}
    <p>Chcesz usunąć swój dostęp do hasła dzielonego "{{ password_obj.description }}"?</p>
    <input class="btn btn-outline-secondary" type="submit" value="Usuń">

</form>

<div style="margin: 30px 0px 30px 0px;">
    <a href="{% url 'password_app:list' %}">
        <button class="btn btn-outline-secondary">Powrót</button>
    </a>
</div>

{% endblock page_content %}

password_webapp_project/templates/password_app/password_update.html
{% extends "base.html" %}
{% load widget_tweaks %}


{% block page_content %}

<div style="margin: 30px 0px 30px 0px;">
    <a href="{% url 'password_app:list' %}">
        <button class="btn btn-outline-secondary">Powrót</button>
    </a>
</div>

<h3>Aktualizuj</h3>

<form method="post" novalidate>
    {% csrf_token %}

    {% for hidden_field in form.hidden_fields %}
    {{ hidden_field }}
    {% endfor %}

    {% if form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {% for error in form.non_field_errors %}
        {{ error }}
        {% endfor %}
    </div>
    {% endif %}

    {% for field in form.visible_fields %}
    <div class="form-group">
        {{ field.label_tag }}

        {% if form.is_bound %}
        {% if field.errors %}
        {% render_field field class="form-control is-invalid col-md-6" %}
        {% for error in field.errors %}
        <div class="invalid-feedback">
            {{ error }}
        </div>
        {% endfor %}
        {% else %}
        {% render_field field class="form-control is-valid col-md-6" %}
        {% endif %}
        {% else %}
        {% render_field field class="form-control col-md-6" %}
        {% endif %}

        {% if field.help_text %}
        <small class="form-text text-muted">{{ field.help_text }}</small>
        {% endif %}
    </div>
    {% endfor %}

    <button type="submit" class="btn btn-outline-secondary">Aktualizuj</button>
</form>

{% endblock page_content %}